development:
  adapter: postgresql
  database: tangopoa_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tangopoa_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tangopoa_production
  pool: 5
  timeout: 5000
