development:
  adapter: postgresql
  database: engage_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: engage_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: engage_production
  pool: 5
  timeout: 5000
